### ISSUE TITLE
Problema cu checkResponse 

### ISSUE THREAD

**Issue by AlloryDante** [vladutilie/euplatesc#1]
Salut, cand folosesc checkResponse cu detaliile din req.body primite din POST-ul de callback de la euplatesc, mereu raspunsul este:
```{ success: false, response: 'invalid' }```

Am folosit cardurile "Approved" recomandate de tine.

req.body pare in regula si pot accesa parametrii:
```
[Object: null prototype] {
  amount: '10.34',
  curr: 'RON',
  invoice_id: '22127',
  ep_id: 'B05420826C5194A96FF142BB043B753C97D30A69',
  merch_id: 'testaccount',
  action: '0',
  message: 'Approved',
  approval: 'tstcrd',
  timestamp: '20230713065305',
  nonce: 'a835a1c191028f813878e567484442e3',
  fp_hash: 'DBA32292AACEB09FF3E3AC0DF1B6F61C',
  'ExtraData[silenturl]': 'https://artadent.ro/paymentcb',
  'ExtraData[successurl]': 'https://artadent.ro/reply'
}
```

Poate sa fie problema ca e cont de test?

**Comment by vladutilie** [comment]
Salut @AlloryDante,

Scuze că revin târziu. Am testat acum metoda `checkResponse` cu body-ul tău și răspunsul primit este `{ success: true, response: 'complete' }`.

Ideea este că trebuie să fii atent la numele câmpurilor și tipurile lor când le transmiți metodei `checkResponse` (vezi [aici](https://www.npmjs.com/package/euplatesc#checkresponse-) la Parameter list). O posibilă adaptare ar putea fi:

```
// ...
const { amount, curr, invoice_id, ep_id, merch_id, action, message, approval, timestamp, nonce, fp_hash } = req.body;
const check = epClient.checkResponse({
    amount,
    currency,
    invoiceId: invoice_id,
    epId: ep_id,
    merchantId: merch_id,
    action,
    message,
    approval,
    timestamp,
    nonce,
    fpHash: fp_hash
});
```

De `ExtraData` nu este nevoie în `checkResponse`.

**Comment by AlloryDante** [comment]
Îti multumesc mult pentru raspuns. Poate am facut eu ceva gresit si o sa reîncerc cu varianta ta. Pentru moment e clar ca este vina implementarii mele si o sa folosesc codul sugerat de tine.

 Multumiri pentru aceasta librarie!

**Comment by vladutilie** [comment]
Nicio problemă, mulțumesc și eu, spor! 🍻
